name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:Version=$VERSION --configuration Release BaldrAI.OpenOTDR.OTDRFile
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create the package
        run: dotnet pack /p:Version=$VERSION --configuration Release BaldrAI.OpenOTDR.OTDRFile
      - name: Publish the package to GPR
        run: dotnet nuget push BaldrAI.OpenOTDR.OTDRFile/bin/Release/*.nupkg